name: mongo
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - accelerate=1.12.0=pyhcf101f3_0
  - aiofiles=25.1.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py310h1eacb63_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anthropic=0.75.0=pyhd8ed1ab_0
  - anyio=4.12.0=pyhcf101f3_0
  - aom=3.9.1=hf036a51_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=hdff831d_0
  - aws-c-cal=0.9.13=hea39f9f_1
  - aws-c-common=0.12.6=h8616949_0
  - aws-c-compression=0.3.1=h901532c_9
  - aws-c-event-stream=0.5.7=ha05da6a_1
  - aws-c-http=0.10.7=h924c446_5
  - aws-c-io=0.23.3=hf559bb5_5
  - aws-c-mqtt=0.13.3=ha72ff4e_11
  - aws-c-s3=0.11.3=he30762a_1
  - aws-c-sdkutils=0.2.4=h901532c_4
  - aws-checksums=0.2.7=h901532c_5
  - aws-crt-cpp=0.35.2=h7484968_6
  - aws-sdk-cpp=1.11.606=hffd60a0_9
  - azure-core-cpp=1.16.1=he2a98a9_0
  - azure-identity-cpp=1.13.2=h0e8e1c8_1
  - azure-storage-blobs-cpp=12.15.0=h388f2e7_1
  - azure-storage-common-cpp=12.11.0=h56a711b_1
  - azure-storage-files-datalake-cpp=12.13.0=h1984e67_1
  - backoff=2.2.1=pyhd8ed1ab_1
  - backports.asyncio.runner=1.2.0=pyhe01879c_2
  - backports.zstd=1.2.0=py310h6194938_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - black=25.12.0=pyha5154f8_0
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - brotli-python=1.2.0=py310hab27952_1
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.6=hb5e19a0_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.3=pyhd8ed1ab_0
  - cairo=1.18.4=h950ec3b_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310h062c7ae_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hf166250_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cryptography=46.0.3=py310h45ec8ab_1
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=h610c526_0
  - datasets=2.14.4=pyhd8ed1ab_0
  - dav1d=1.2.1=h0dc2134_0
  - dbus=1.16.2=h6e7f9a9_1
  - deepsearch-glm=1.0.0=py310h3c13618_8
  - deprecated=1.3.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - dnspython=2.8.0=pyhcf101f3_0
  - docling=2.15.1=pyh29332c3_0
  - docling-core=2.44.2=pyhe01879c_0
  - docling-ibm-models=3.10.3=pyhcf101f3_0
  - docstring_parser=0.17.0=pyhd8ed1ab_0
  - double-conversion=3.3.1=h240833e_0
  - easyocr=1.7.2=py310hf76f91c_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - eval-type-backport=0.3.1=pyhd8ed1ab_0
  - eval_type_backport=0.3.1=pyha770c72_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fasta2a=0.6.0=pyhcf101f3_0
  - fasttext-for-deepsearch-glm=0.1.0=np2py310h1d90035_5
  - ffmpeg=8.0.1=gpl_h1953588_106
  - filelock=3.20.0=pyhd8ed1ab_0
  - filetype=1.2.0=pyhd8ed1ab_0
  - fmt=12.0.0=h7a3a4f9_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hd951482_0
  - freetype=2.14.1=h694c41f_0
  - fribidi=1.0.16=h8616949_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h07555a4_0
  - genai-prices=0.0.48=pyhcf101f3_0
  - geos=3.14.1=he483b9e_0
  - gflags=2.2.2=hac325c4_1005
  - giflib=5.2.2=h10d778d_0
  - glog=0.7.1=h2790a97_0
  - glslang=16.1.0=h4770549_0
  - gmp=6.3.0=hf036a51_2
  - gmpy2=2.2.1=py310h18a5c99_2
  - google-auth=2.43.0=pyhd8ed1ab_0
  - google-genai=1.55.0=pyhcf101f3_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - graphite2=1.3.14=h21dd04a_2
  - griffe=1.15.0=pyhd8ed1ab_0
  - groq=0.37.1=pyhd8ed1ab_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=hc5d3ef4_0
  - hdf5=1.14.6=nompi_hc1508a4_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.11=pyhd8ed1ab_0
  - imageio=2.37.0=pyhfb79c49_0
  - imath=3.2.2=h55e386d_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jasper=4.2.8=h9ce442b_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jiter=0.12.0=py310hf24d99c_1
  - jmespath=1.0.1=pyhd8ed1ab_1
  - json_schema_validator=2.4.0=hfc0b2d5_0
  - jsonlines=4.0.0=pyhd8ed1ab_0
  - jsonref=1.1.0=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - kiwisolver=1.4.9=py310h355fb9f_2
  - krb5=1.21.3=h37d8d59_0
  - lame=3.100=hb7f2c08_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20250512.1=cxx17_hfc00f1c_0
  - libaec=1.1.4=ha6bc127_0
  - libarrow=22.0.0=hd1700fa_4_cpu
  - libarrow-acero=22.0.0=h2db2d7d_4_cpu
  - libarrow-compute=22.0.0=h7751554_4_cpu
  - libarrow-dataset=22.0.0=h2db2d7d_4_cpu
  - libarrow-substrait=22.0.0=h4653b8a_4_cpu
  - libass=0.17.4=h87c4fc2_0
  - libavif16=1.3.0=h1c10324_2
  - libblas=3.9.0=20_osx64_mkl
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcblas=3.9.0=20_osx64_mkl
  - libclang-cpp19.1=19.1.7=default_hc369343_5
  - libclang13=21.1.7=default_h7f9524c_1
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.17.0=h7dd4100_1
  - libcxx=21.1.7=h3d58e20_0
  - libde265=1.0.15=h7728843_0
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=h750e83c_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgcc=15.2.0=h08519bb_15
  - libgfortran=15.2.0=h7e5c614_15
  - libgfortran5=15.2.0=hd16e46c_15
  - libglib=2.86.2=h6ca3a76_0
  - libgoogle-cloud=2.39.0=hed66dea_0
  - libgoogle-cloud-storage=2.39.0=h8ac052b_0
  - libgrpc=1.73.1=h451496d_1
  - libheif=1.19.7=gpl_h95ec88c_100
  - libhwloc=2.12.1=default_h273dbb7_1003
  - libhwy=1.3.0=hab838a1_1
  - libiconv=1.18=h57a12c2_2
  - libintl=0.25.1=h3184127_1
  - libjpeg-turbo=3.1.2=h8616949_0
  - libjxl=0.11.1=h4ee1b5b_5
  - liblapack=3.9.0=20_osx64_mkl
  - liblapacke=3.9.0=20_osx64_mkl
  - libllvm19=19.1.7=h56e7563_2
  - libllvm21=21.1.7=h56e7563_0
  - liblzma=5.8.1=hd471939_2
  - libnghttp2=1.67.0=h3338091_0
  - libntlm=1.8=h6e16a3a_0
  - libogg=1.3.5=he3325bb_1
  - libopencv=4.12.0=qt6_py310h0bbbe20_609
  - libopentelemetry-cpp=1.21.0=h7d3f41d_1
  - libopentelemetry-cpp-headers=1.21.0=h694c41f_1
  - libopenvino=2025.2.0=h346e020_1
  - libopenvino-auto-batch-plugin=2025.2.0=heda8b29_1
  - libopenvino-auto-plugin=2025.2.0=heda8b29_1
  - libopenvino-hetero-plugin=2025.2.0=hd57c75b_1
  - libopenvino-intel-cpu-plugin=2025.2.0=h346e020_1
  - libopenvino-ir-frontend=2025.2.0=hd57c75b_1
  - libopenvino-onnx-frontend=2025.2.0=ha4fb624_1
  - libopenvino-paddle-frontend=2025.2.0=ha4fb624_1
  - libopenvino-pytorch-frontend=2025.2.0=hbc7d668_1
  - libopenvino-tensorflow-frontend=2025.2.0=hd87add6_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hbc7d668_1
  - libopus=1.5.2=he3325bb_0
  - libparquet=22.0.0=habb56ca_4_cpu
  - libpng=1.6.53=h380d223_0
  - libpq=18.1=h1e038c5_2
  - libprotobuf=6.31.1=h03562ea_2
  - libre2-11=2025.11.05=h554ac88_0
  - librsvg=2.60.0=h2da6fc3_0
  - libsentencepiece=0.2.1=hd3898f4_1
  - libspatialindex=2.1.0=h501a4e1_0
  - libsqlite=3.51.1=h6cc646a_0
  - libssh2=1.11.1=hed3591d_0
  - libthrift=0.22.0=h687e942_1
  - libtiff=4.7.1=ha0a348c_1
  - libtorch=2.9.1=cpu_mkl_h43f2b17_101
  - libusb=1.0.29=h2287256_0
  - libutf8proc=2.11.2=h7983711_0
  - libuv=1.51.0=h58003a5_1
  - libvorbis=1.3.7=ha059160_2
  - libvpx=1.15.2=heffb93a_0
  - libvulkan-loader=1.4.328.1=hfc0b2d5_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.15.1=h7b7ecba_0
  - libxml2-16=2.15.1=ha1d9b0f_0
  - libxslt=1.1.43=h486b42e_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.7=h472b3d1_0
  - logfire=4.16.0=pyhd8ed1ab_0
  - loguru-cpp=2.1.0.post20230406.4adaa18=hd6aca1a_1
  - lxml=6.0.2=py310ha2fbfbd_2
  - lz4-c=1.10.0=h240833e_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - marko=2.2.1=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310hd951482_0
  - matplotlib-base=3.10.8=py310h2102b89_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2023.2.0=h694c41f_50502
  - more-itertools=10.8.0=pyhcf101f3_1
  - mpc=1.3.1=h9d8efa1_1
  - mpfr=4.2.1=haed47dc_3
  - mpire=2.10.2=pyhd8ed1ab_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - ncurses=6.5=h0622a9a_3
  - networkx=3.4.2=pyh267e887_2
  - ninja=1.13.2=hfc0b2d5_0
  - nlohmann_json=3.12.0=h53ec75d_1
  - numba=0.63.1=py310hce29faf_0
  - numpy=2.2.6=py310h07c5b4d_0
  - openai=2.9.0=pyhd8ed1ab_0
  - openai-agents=0.6.3=pyhcf101f3_0
  - openai-whisper=20250625=pyhd8ed1ab_0
  - openexr=3.4.4=hdc8e27a_0
  - openh264=2.6.0=h4883158_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openjph=0.25.3=h00f0702_0
  - openldap=2.6.10=hd8a590d_0
  - openpyxl=3.1.5=py310h20ca25a_2
  - openssl=3.6.0=h230baf5_0
  - opentelemetry-api=1.39.1=pyhd8ed1ab_0
  - opentelemetry-instrumentation=0.60b1=pyhd8ed1ab_0
  - opentelemetry-sdk=1.39.1=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.60b1=pyhd8ed1ab_0
  - optree=0.18.0=py310h8cf47bc_0
  - orc=2.2.1=hd1b02dc_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h39ce848_1
  - pango=1.56.4=h6ef8af8_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre2=10.46=ha3e7e28_0
  - pillow=11.3.0=py310h566a92c_3
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=ha059160_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - prometheus-cpp=1.3.0=h7802330_0
  - psutil=7.1.3=py310h3aa7efa_0
  - pthread-stubs=0.4=h00291cd_1002
  - pugixml=1.15=h46091d4_0
  - py-opencv=4.12.0=qt6_py310h25f5310_609
  - pyarrow=22.0.0=py310h2ec42d9_0
  - pyarrow-core=22.0.0=py310hca48698_0_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-ai=1.29.0=pyhcf101f3_0
  - pydantic-core=2.41.5=py310h64024f4_1
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymongo=4.15.5=py310ha75780e_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.2=pyhcf101f3_0
  - pytest-asyncio=1.3.0=pyhcf101f3_0
  - python=3.10.19=h988dfef_2_cpython
  - python-bidi=0.6.7=py310hf24d99c_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-docx=1.2.0=pyhff2d567_0
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-gil=3.10.19=hd8ed1ab_2
  - python-multipart=0.0.20=pyhff2d567_0
  - python-pptx=1.0.2=pyh29332c3_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py310hb4a031f_1
  - python_abi=3.10=8_cp310
  - pytokens=0.3.0=pyhcf101f3_0
  - pytorch=2.9.1=cpu_mkl_py310_h4362b24_101
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywavelets=1.8.0=py310h6fa6179_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.3=py310hd951482_0
  - qhull=2020.2=h3c5361c_5
  - qpdf=11.10.1=h1b4af3b_0
  - qt6-main=6.9.3=hac9256e_1
  - rav1e=0.7.1=h371c88c_3
  - re2=2025.11.05=h7df6414_0
  - readline=8.2=h7cca4af_2
  - regex=2025.11.3=py310hd2d5e8d_1
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=13.9.4=pyhd8ed1ab_1
  - rpds-py=0.30.0=py310h64024f4_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - rtree=1.4.1=pyh11ca60a_0
  - ruff=0.14.8=hd9f4cfa_0
  - s3transfer=0.16.0=pyhd8ed1ab_0
  - safetensors=0.7.0=py310hf24d99c_0
  - scikit-image=0.25.2=py310h39ce848_2
  - sdl2=2.32.56=h53ec75d_0
  - sdl3=3.2.28=h53c92ef_0
  - semchunk=2.2.2=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.5=hda4194c_0
  - shapely=2.1.2=py310hd250500_2
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h289094c_0
  - snappy=1.2.2=h01f5ddf_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - spirv-tools=2025.4=hcb651aa_0
  - sse-starlette=3.0.3=pyhd8ed1ab_0
  - starlette=0.50.0=pyhfdc7a7d_0
  - svt-av1=3.1.2=h21dd04a_0
  - sympy=1.14.0=pyh2585a3b_105
  - tabulate=0.9.0=pyhcf101f3_3
  - tbb=2021.13.0=hf0c99ee_4
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tifffile=2025.2.18=py310hecd8cb5_0
  - tiktoken=0.12.0=py310h813fcaf_3
  - tk=8.6.13=hf689a15_3
  - tomli=2.3.0=pyhcf101f3_0
  - torchvision-extra-decoders=0.0.2=py310h05a858d_5
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.57.3=pyhd8ed1ab_0
  - typer-slim=0.12.5=pyhd8ed1ab_0
  - typer-slim-standard=0.12.5=hd8ed1ab_0
  - types-requests=2.32.4.20250913=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - unicodedata2=17.0.0=py310hd2d5e8d_1
  - uvicorn=0.38.0=pyh31011fe_0
  - websockets=15.0.1=py310h0818920_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py310h1b7cace_1
  - x264=1!164.3095=h775f41a_2
  - x265=3.5=hbb4e6a2_3
  - xlsxwriter=3.2.9=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - xxhash=0.8.3=h13e91ac_0
  - yaml=0.2.5=h4132b18_3
  - yarl=1.22.0=py310hd951482_0
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hd23fc13_2
  - zstd=1.5.7=h3eecb57_6
  - pip:
      - ag-ui-protocol==0.1.10
      - antlr4-python3-runtime==4.9.3
      - argcomplete==3.6.3
      - authlib==1.6.6
      - backports-tarfile==1.2.0
      - beartype==0.22.9
      - boto3==1.42.9
      - botocore==1.42.9
      - cloudpickle==3.1.2
      - cohere==5.20.0
      - colorlog==6.10.1
      - cyclopts==4.3.0
      - dill==0.4.0
      - diskcache==5.6.3
      - docling-parse==4.7.2
      - docutils==0.22.3
      - email-validator==2.3.0
      - faker==38.2.0
      - fakeredis==2.32.1
      - fastavro==1.12.1
      - fastmcp==2.14.0
      - frozenlist==1.8.0
      - hf-xet==1.2.0
      - httpx-sse==0.4.0
      - invoke==2.2.1
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jsonschema-path==0.3.4
      - keyring==25.7.0
      - latex2mathml==3.78.1
      - llvmlite==0.46.0
      - logfire-api==4.16.0
      - lupa==2.6
      - mcp==1.24.0
      - mistralai==1.9.11
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nexus-rpc==1.2.0
      - ocrmac==1.0.0
      - omegaconf==2.3.0
      - openapi-pydantic==0.5.1
      - opencv-python==4.12.0.88
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-http==1.39.1
      - opentelemetry-exporter-prometheus==0.60b1
      - opentelemetry-instrumentation-httpx==0.60b1
      - opentelemetry-proto==1.39.1
      - opentelemetry-util-http==0.60b1
      - pathable==0.4.4
      - pathvalidate==3.3.1
      - polyfactory==3.1.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.2
      - py-key-value-aio==0.3.0
      - py-key-value-shared==0.3.0
      - pyclipper==1.4.0
      - pycparser==2.23
      - pydantic-ai-slim==1.32.0
      - pydantic-evals==1.32.0
      - pydantic-graph==1.32.0
      - pydocket==0.15.5
      - pyjwt==2.10.1
      - pylatexenc==2.10
      - pyobjc-core==12.1
      - pyobjc-framework-cocoa==12.1
      - pyobjc-framework-coreml==12.1
      - pyobjc-framework-quartz==12.1
      - pyobjc-framework-vision==12.1
      - pypdfium2==4.30.0
      - pyperclip==1.11.0
      - python-json-logger==4.0.0
      - rapidocr==3.4.3
      - redis==7.1.0
      - referencing==0.36.2
      - rich-rst==1.3.2
      - scipy==1.15.3
      - sortedcontainers==2.4.0
      - temporalio==1.20.0
      - tokenizers==0.22.1
      - torch==2.2.2
      - torchvision==0.17.2
      - tree-sitter==0.25.2
      - tree-sitter-c==0.24.1
      - tree-sitter-java==0.23.5
      - tree-sitter-javascript==0.25.0
      - tree-sitter-python==0.25.0
      - tree-sitter-typescript==0.23.2
      - typer==0.19.2
      - types-protobuf==6.32.1.20251210
      - tzdata==2025.3
      - urllib3==2.6.2
      - wcwidth==0.2.14
prefix: /opt/miniconda3/envs/mongo
